import os
import datetime
import logging
import boto3
import pytz

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)

ACCESS_KEY = os.getenv("ACCESS_KEY")
SECRET_KEY = os.getenv("SECRET_KEY")
BUCKET_NAME = os.getenv("BUCKET_NAME")
TIME_ZONE = os.getenv("TIME_ZONE", "UTC")

TEMP_FILE = "/tmp/file.txt"

# Initialize the client once (optimal for serverless)
s3_client = boto3.client(
    "s3",
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY,
    endpoint_url="https://storage.yandexcloud.net",
)


def validate_env():
    if not ACCESS_KEY or not SECRET_KEY or not BUCKET_NAME:
        raise ValueError("Missing required environment variables")


def create_file():
    with open(TEMP_FILE, "w") as f:
        f.write("Generated by cloud function")
    logger.info("Temp file created")


def get_time():
    now = datetime.datetime.now(pytz.timezone(TIME_ZONE))
    return now.strftime("%Y-%m-%d_%H-%M-%S")


def upload():
    key = f"file-{get_time()}.txt"

    logger.info(f"Uploading file to bucket={BUCKET_NAME}, key={key}")

    s3_client.upload_file(
        TEMP_FILE,
        BUCKET_NAME,
        key
    )

    logger.info("Upload successful")


def cleanup():
    if os.path.exists(TEMP_FILE):
        os.remove(TEMP_FILE)
        logger.info("Temp file removed")


def handler(event, context):
    logger.info("Upload function invoked")

    try:
        validate_env()

        if context:
            logger.info(f"Request ID: {getattr(context, 'request_id', 'unknown')}")

        create_file()
        upload()

        return {
            "statusCode": 200,
            "body": "File uploaded successfully"
        }

    except Exception as e:
        logger.exception("Function failed")  # <-- quite important!

        return {
            "statusCode": 500,
            "body": "Internal error"
        }

    finally:
        cleanup()
